[env:ttgo-t1]
platform = espressif32
board = ttgo-t1
board_build.partitions = 16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
lib_ldf_mode = deep
lib_deps = codewitch-honey-crisis/htcw_ttgo
upload_port = COM23
monitor_port = COM23
